routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/templates/home');
});

Route::resource('/users','userController');
Route::resource('/categories','CategoryController');
Route::resource('/books','BookController');
Route::resource('/orders','OrderController');

Route::get('/users/search/email', 'userController@search')->name('users.search');
Route::get('/books/search/title', 'BookController@search')->name('books.search');
Route::get('/categories/search/category', 'CategoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'OrderController@search')->name('orders.search');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'Judul', 'Sinopsis', 'penulis', 'publisher', 'cover', 'harga', 'stok'
    ];

    public function category() {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Category;

class BookController extends Controller
{
    public function index()
    {
        $books = Book::paginate(5);
        return view('books.index', compact('books'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('books.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $request->validate([
          'Judul' => 'required',
          'Sinopsis' => 'required|max:200',
          'penulis' => 'required',
          'publisher' => 'required',
          'harga' => 'required|numeric|max:999999',
          'stok' => 'required|numeric',
          'kategori'=> 'required',
          'cover' => 'image',
        ]);

        $buku_baru = new Book();
        $buku_baru->Judul = $request->get('Judul');
        $buku_baru->Sinopsis = $request->get('Sinopsis');
        $buku_baru->penulis = $request->get('penulis');
        $buku_baru->publisher = $request->get('publisher');
        $buku_baru->harga = $request->get('harga');
        $buku_baru->stok = $request->get('stok');
        if ($request->file('cover')) {
            $file = $request->file('cover')->store('cover','public');
            $buku_baru->cover = $file;
        }
        $buku_baru->save();

        $buku_baru->category()->attach($request->get('kategori'));

        return redirect()->route('books.index')->with('status','Book succesfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::findOrFail($id);
        return view('books.show',['book'=>$book]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $categories = Category::all();
        return view('books.edit',['book'=>$book, 'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
          'Judul' => 'required',
          'Sinopsis' => 'required|max:200',
          'penulis' => 'required',
          'publisher' => 'required',
          'harga' => 'required|numeric|max:999999',
          'stok' => 'required|numeric',
          'kategori'=> 'required',
        ]);

        $ubah_buku = Book::findOrFail($id);
        $ubah_buku->Judul = $request->get('Judul');
        $ubah_buku->Sinopsis = $request->get('Sinopsis');
        $ubah_buku->penulis = $request->get('penulis');
        $ubah_buku->publisher = $request->get('publisher');
        $ubah_buku->harga = $request->get('harga');
        $ubah_buku->stok = $request->get('stok');
        if ($request->file('cover')) {
            if ($ubah_buku->cover && file_exists(storage_path('storage/'.$ubah_buku->cover))) {
                Storage::delete('storage/'.$ubah_buku->cover);
            }
            $file = $request->file('cover')->store('cover','public');
            $ubah_buku->cover = $file;
        }
        $ubah_buku->save();

        $ubah_buku->category()->sync($request->get('kategori'));

        return redirect()->route('books.index',['id'=>$id])->with('status','Book succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
         $book = Book::findOrFail($id);
         if ($book->cover && file_exists(storage_path('public/storage/'.$book->cover))) {
             Storage::delete('public/storage/'.$book->cover);
         }
         $book->delete();
         return redirect()->route('books.index')->with('status', 'Book Successfully deleted');
     }

     public function search(Request $request)
     {
         $books = Book::when($request->found, function ($query) use ($request) {
             $query->where('Judul', 'like', "%{$request->found}%");
             // orWhere('Sinopsis', 'like', "%{$request->found}%");
         })->paginate(5);

         $books->appends($request->only('found'));

         return view('books.index', compact('books'));
     }
}

resources/views/books/create.blade.php
@extends('templates.home')
@section('Judul')
    Create Books
@endsection
@section('content')
    <div class="container" >
      <br><br>
        <h3>Create Books</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Books</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="Judul" >Judul</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="Judul" id="Judul">
                                {{ ($errors->has('Judul')) ? $errors->first('Judul') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="penulis">Penulis</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="penulis" id="penulis">
                                {{ ($errors->has('penulis')) ? $errors->first('penulis') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="publisher">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="publisher" id="publisher">
                                {{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="harga">Harga</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="harga" id="harga">
                                {{ ($errors->has('harga')) ? $errors->first('harga') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stok">Stok</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="stok" id="stok">
                                {{ ($errors->has('stok')) ? $errors->first('stok') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="Sinopsis">Sinopsis</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control" name="Sinopsis" id="Sinopsis" rows="6" >

                                </textarea>
                                {{ ($errors->has('Sinopsis')) ? $errors->first('Sinopsis') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="kategori">Kategori</label>
                            </div>
                            <div class="col-md-8">
                                <select multiple='multiple' name="kategori[]" id="kategori" class="form-control {{$errors->first('kategori') ? "is-invalid": ""}}">
                                    <option value="">Select Kategori</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->genre }}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    {{$errors->first('kategori')}}
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
              						<div class="input-group mb-3">
              							<div class="col-md-3 text-primary">
              								Cover
              							</div>

              							<div class="col-md-8">
              								<div class="custom-file">
                									<input type="file" class="custom-file-input" name="cover" id="newAvatar">
                									<label class="custom-file-label" for="newAvatar">Upload Cover</label>
              									  {{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
              								</div>
              							</div>
              						</div>
              					</div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('templates.home')
@section('Judul')
    Edit Book
@endsection
@section('content')
    <div class="container" >
        <h3>Form Edit Book</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $book['Judul'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.update',$book['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        @csrf
                        @method('PUT')
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="Judul">Judul</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="Judul" id="Judul" value=" {{ $book['Judul'] }}">
                                {{ ($errors->has('Judul')) ? $errors->first('Judul') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="penulis">Penulis</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="penulis" id="penulis" value=" {{ $book['penulis'] }}">
                                {{ ($errors->has('penulis')) ? $errors->first('penulis') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="publisher">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="publisher" id="publisher" value="{{ $book['publisher'] }}">
                                {{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="harga">Harga</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="harga" id="harga" value=" {{ $book['harga'] }}">
                                {{ ($errors->has('harga')) ? $errors->first('harga') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stok">Stok</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="stok" id="stok" value="{{ $book['stok'] }}">
                                {{ ($errors->has('stok')) ? $errors->first('stok') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="deskripsi">Sinopsis</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control" name="Sinopsis" id="deskripsi" rows="6">
                                    {{ $book['Sinopsis'] }}
                                </textarea>
                                {{ ($errors->has('Sinopsis')) ? $errors->first('Sinopsis') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="kategori">Category</label>
                            </div>
                            <div class="col-md-8">
                              @foreach($book->category as $category)
                                  <span class="badge badge-primary">{{ $category->genre }}  </span>
                              @endforeach
                                <select multiple='multiple' name="kategori[]" id="kategori" class="form-control {{$errors->first('kategori') ? "is-invalid": ""}}">
                                    <option value="">Select Category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->genre }}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    {{$errors->first('kategori')}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
              						<div class="input-group mb-3">
              							<div class="col-md-3 text-primary">
              								Cover
              							</div>

              							<div class="col-md-8">
              								<img src=" {{ asset('storage/'.$book['cover']) }} " alt="gambar" class="img-thumbnail" height="150px" width="150px">
              								<div class="custom-file">
                									<input type="file" class="custom-file-input" name="cover" id="newAvatar">
                									<label class="custom-file-label" for="newAvatar">Upload Cover</label>
              									  {{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
              								</div>
              							</div>
              						</div>
              					</div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/index.blade.php
@extends('templates.home')
@section('title')
    List of Books
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>List of Books</h3>
        <hr>

        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-outline-primary " href="{{ route('books.create') }}">
                    <span data-feather="plus-circle"></span>
                    Create a new book <span class="sr-only">(current)</span>
                </a>
            </div>
            <div class="col-md-8">
          			<form action="{{ route('books.search') }}" class="form-inline" method="GET">
          			    <div class="form-group mx-sm-3 mb-2">
          			         <input class="form-control" name="found" placeholder="Search by Title..." value="{{ old('found') }}" style="width: 550px;">
          			    </div>
          			    <button class="btn btn-primary mb-2" type="submit">Search</button>
          			</form>
      			</div>
        </div>
        <br>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">No</th>
                        <th scope="col">Judul</th>
                        <th scope="col">Penulis</th>
                        <th scope="col">Publisher</th>
                        <th scope="col">Cover</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>{{ $book['id'] }}</td>
                            <td>{{ $book['Judul'] }}</td>
                            <td>{{ $book['penulis'] }}</td>
                            <td>{{ $book['publisher'] }}</td>
                            <td> <img src="{{ 'storage/'.$book['cover'] }}" alt="" width="100px" height="100px"> </td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('books.show',$book['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('books.edit',$book['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this book permanently?')"
                                    action="{{route('books.destroy', $book['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="" style="margin: auto; width: 150px;">
                {{ $books->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/books/show.blade.php
@extends('templates.home')
@section('title')
    Detail of Book
@endsection
@section('content')
    <h1>Detail of Book </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:400px;">
        <div class="row " style="padding:25px">
            <div class="col-md-2 offset-md-5 offset-sm-4">
                <img src="{{ asset('storage/'.$book['cover']) }}" style="height:150px; width:150px; color:black;" class="rounded-circle" alt="img">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>{{ $book['Judul'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Penulis
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['penulis'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Publisher
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['publisher'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Harga
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['harga'] }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Stok
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['stok'] }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Sinopsis
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['Sinopsis'] }}
            </div>
        </div>
        <div class="row">
    			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
    				Kategori
    			</div>
    			<div class="col-md-4 col-sm-4">
    				<ul>
    				@foreach ($book->category as $categories)
    					   <li>{{ $categories->genre }}</li>
    				@endforeach
    				</ul>
    			</div>
    		</div>
    </div>
@endsection